---
fixtures:
  repositories:
    augeasproviders_core: "git://github.com/simp/augeasproviders_core"
    augeasproviders_grub: "git://github.com/simp/augeasproviders_grub"
    simplib              : "git://github.com/simp/pupmod-simp-simplib"
    simpcat              : "git://github.com/simp/pupmod-simp-concat"
    iptables            : "git://github.com/simp/pupmod-simp-iptables"
    oddjob              : "git://github.com/simp/pupmod-simp-oddjob"
    pam                 : "git://github.com/simp/pupmod-simp-pam"
    rsync               : "git://github.com/simp/pupmod-simp-rsync"
    stdlib              : "git://github.com/simp/puppetlabs-stdlib"
    sudo                : "git://github.com/simp/pupmod-simp-sudo"
    xinetd              : "git://github.com/simp/pupmod-simp-xinetd"
    xwindows            : "git://github.com/simp/pupmod-simp-xwindows"
  symlinks:
    vnc: "#{source_dir}"
